### ISSUE TITLE
No module named 'lib' - ImportError: cannot import name 'whisper' from partially initialized module 'pysubs2' 

### ISSUE THREAD

**Issue by peno64** [bkiziuk/script.module.pysubs2#1]
Hello,

I am using pysub2 in a kodi subtitle addon I wrote (localsubtitle) and  with the latest update 1.5 I get following error.

Have you tested  this update with an addon and should something be changed to the addon for this new version?

2022-12-04 09:24:57.327 T:16868   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'lib'
                                                   Traceback (most recent call last):
                                                     File "C:\kodi19\Kodi\portable_data\addons\service.subtitles.localsubtitle\service.py", line 16, in <module>
                                                       import pysubs2
                                                     File "C:\kodi19\Kodi\portable_data\addons\script.module.pysubs2\lib\pysubs2\__init__.py", line 4, in <module>
                                                       from . import time, formats, cli, whisper
                                                   ImportError: cannot import name 'whisper' from partially initialized module 'pysubs2' (most likely due to a circular import) (C:\kodi19\Kodi\portable_data\addons\script.module.pysubs2\lib\pysubs2\__init__.py)

                                                   During handling of the above exception, another exception occurred:

                                                   Traceback (most recent call last):
                                                     File "C:\kodi19\Kodi\portable_data\addons\service.subtitles.localsubtitle\service.py", line 18, in <module>
                                                       from lib import pysubs2
                                                   ModuleNotFoundError: No module named 'lib'
                                                   -->End of Python script error report<--

**Comment by peno64** [comment]
See  https://github.com/tkarabela/pysubs2/commit/12e93793c86b6b3d417e694cccf6fb2b13129e53#diff-61ef7750f70614a1c0fb4972ecf0c73ed442ea0da67776e18b898b7d6143d403
whisper.py is a new file that was  added and you didn't put it in your repo

**Comment by peno64** [comment]
@bkiziuk 
I can confirm that just adding this file whisper.py solves the problem. Please  make an update of your repo asap.

**Comment by bkiziuk** [comment]
@peno64 
Yes, indeed. I forgot to add it to git. Already corrected. Many thanks for pointing that out.
